[package]
name = "hf"
version = "0.1.0"
authors = ["Salem Yaslem <s@sy.sa>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
